### ISSUE TITLE
more field checking

### ISSUE THREAD

**Issue by MattWiener** [EHDEN/ApplicationPortals#11]
1.  If we are going to ask for number of employees, we should check that it's below the limit to be an SME.
2.  If we are going to ask for turnover, we should specify units and then check that it's below the limit.
3.  I put in a phrase as a phone number.  Shouldn't be able to.
4.  I would suggest that area of activity be a drop-down instead of free text (or removed entirely - what are we going to use it for?).   Similarly for function.
5. possibly "legal form" should also be a drop-down.   And again, what do we want this information for?

**Comment by PRijnbeek** [comment]
1. Yes. Just fixed this related to this issue post: https://github.com/EHDEN/ApplicationPortals/issues/3
2. We can specify in the text (in euros) indeed. We can then add number validation. Maximum check is not possible as far as I can see, also think this will not really be a problem. We can check these numbers as well easily in the process.
3. :) agree but you should simply not do this. Phone number validation is not possible as far as I can see but will check
4. This is not new, see forum discussions, we are not iterating over fields again. Field of activity is very important to know, e.g. are they active in Health Care? If you suggest drop-down please specify the fields.
5. Could drop it, but it also does not hurt to know. This was not put forward earlier in the development process when we agreed on the form.

**Comment by PRijnbeek** [comment]
2. done added (euro) in the text
4. we will leave it as is and see how the SMEs will fill this in and evaluate.

Closing this issue can be re-opened  by @MattWiener if problems with the replies.
