### ISSUE TITLE
submission button

### ISSUE THREAD

**Issue by MattWiener** [EHDEN/ApplicationPortals#13]
I found it confusing that the submission button shows up in a separate space from the application form.   I would put it above, near the "view" and "edit" buttons.    It can be grayed out initially, perhaps with a tooltip or text saying that it will turn green when the application is complete.

**Comment by PRijnbeek** [comment]
This can not changed, sorry. It is greyed out initially, and becomes green. (I think this is mentioned in the instruction text above, but will check).

**Comment by PRijnbeek** [comment]
Is indeed mentioned above. Close this issue now.
