### ISSUE TITLE
e-mail on receipt of application

### ISSUE THREAD

**Issue by MattWiener** [EHDEN/ApplicationPortals#14]
Hi.   I found the sentence "The SME Committee will review all the submitted applications and will prioritise those that will be allowed to enter the current training and certification round." annoying, probably because of the use of "allowed".   

How about something like:  "The selection committee will review submitted applications, and schedule those that are accepted into available training sessions."

This would require we have multiple trainings planned, perhaps.   I am open to other suggestions that get rid of the word "allowed".    Perhaps even "... will select some for the current training and certification round.  If not scheduled for the current round, you may be offered a place in a later round."

Does anyone else have this reaction to "allowed"?

**Comment by PRijnbeek** [comment]
Thanks, see my request here:
https://forum.ehden.eu/t/input-needed-on-the-auto-emails/316

I see your point though. Fine for me to change now.

**Comment by PRijnbeek** [comment]
I have changed it to "prioritise those that will be selected for the current training and certification round"
