### ISSUE TITLE
Profile creation page

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#15]
_After you created your profile, you need to fill in an application form that will be reviewed by an **independent committee**. For more information about the SME call please see our website (link to be added)._

I don't know if it'll happen down the line, but perhaps we could link to the governance board page on the website and explain it more in detail there? as an applicant, I would like to know who and how my application will be judged.

**Comment by PRijnbeek** [comment]
Agree, but the idea was this would be in the SME Call document (the next sentence).
We could make this more explicit maybe by saying this in that sentence.

**Comment by PRijnbeek** [comment]
made more explicit by adding: "information about the SME call and the review process"
