### ISSUE TITLE
Can't delete my company profile?

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#16]
After creating the profile, I get the option to see my profile, and to edit details. What I miss is a button to delete my profile? (Unless I missed it). 

I don't know if it's possible in the system to allow this, but if not we should make it clear on the company profile page that they should contact person X to get their details deleted from the system.

**Comment by PRijnbeek** [comment]
They cannot themselves, but we can add it in the privacy statement under opt out. It would mean we remove all information. If you take this on, please close the issue afterwards.

**Comment by JellePraet** [comment]
I'll make sure it's in there.
