### ISSUE TITLE
Suggestions - 

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#17]
On the page where you create/enter your company details:

- Should we limit the countries in the drop down list to EU countries only? + Include a firm statement that we are only looking for EU companies? Just trying to reduce admin overburden due to invalid applications :)

- For the address lines : street + number instead of just street?

- For the telephone numbers: indicate which format you expect it to be (eg +32 (3) 123 45 67 )

**Comment by PRijnbeek** [comment]
1) this is not possible unless we make our own dropdown with all the countries. If you have such a list we could it is just a lot of work.

2) mm don't know it is pretty obvious it think and generally used as such

3) We can not validate it in the field but if you think there are people that will not add the country code as in the example we can add the example sure.

**Comment by PRijnbeek** [comment]
1. added a statement that only European SMEs are eligible.

2. Solved now by using Street Address instead and a clarification in the help text

3. Added help text.
