### ISSUE TITLE
Application form 

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#19]
I had problems entering words/numbers in the answer boxes of 2 questions : 
* How many people could you dedicate to a single data conversion at a time?	
* How many such teams could you field at the same time?

Don't know if it was just my pc acting up or whether these fields had restrictions. In case of the latter, indicate those restrictions to avoid confusion?

**Comment by PRijnbeek** [comment]
These are number fields since they require a number (how many?). Why did you want to fill in text?

**Comment by fgiesen** [comment]
I have the same issue. This is impossible to fill in any number or text in those two fields. 
I tried to exit and go back to the page, it remains stuck. This is a blocking issue as it is impossible to submit the form without having those fields filled in.

**Comment by PRijnbeek** [comment]
You say that if you fill for example: 2 it does not accept it?

**Comment by fgiesen** [comment]
Using the num pad or setting the CAPS LOCK on on my keyboard allowed me to enter the numbers.
The issue seems to appear on an AZERTY keyboard only.

**Comment by fgiesen** [comment]
Seems to be related to the simultaneous key pressing of shift + number.

I think this issue should be reported to WizeHyve.

**Comment by PRijnbeek** [comment]
Thanks we can fix this by changing the field type, i will do a test with you once this is done.

Will also report it to WizeHive.

**Comment by fgiesen** [comment]
I am not sure, but this issue might be present with other "numbers only" fields (to be tested)

**Comment by fgiesen** [comment]
Thank you Peter for your reactivity !

**Comment by PRijnbeek** [comment]
There are only two Number fields in the form. Could easily make them text as well of course that would solve the problem and will have zero effect on our evaluation.

**Comment by PRijnbeek** [comment]
These fields are changed to Text which solves this problem. See also #34
