### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by lhjohn** [EHDEN/ApplicationPortals#2]
### Applicant profile

- [x] _Annual turnover 2018_ should probably be capitalized to _Annual Turnover 2018_ to be consistent with the rest of the headings
- [x] _Number of Employees as of December 31th 2018_ should be _Number of Employees as of December 31st 2018_
- [x] Instead of _Internet Address_ I would use _Website_

**Comment by lhjohn** [comment]
### Award Acceptance short intro text
- [ ] _Congratulations_ should be followed by period or exclamation mark
- [ ] Typo in _condictions_

**Comment by PRijnbeek** [comment]
Thanks all changes accordingly
