### ISSUE TITLE
Application submission confirmation email

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#20]
In the confirmation email i received it says: "Our aim is to review your application within four business weeks"

If I submit my application on April 1st, I will not have my answer 4 weeks thereafter as the call would still be running. I suggest rephrasing and putting in the actual date by when we have the results available?

**Comment by PRijnbeek** [comment]
Agree this is an open question as asked for here:
https://forum.ehden.eu/t/input-needed-on-the-auto-emails/316

Once a decision is made and the text is changed accordingly we will close the issue

**Comment by PRijnbeek** [comment]
Now the closure date is set to May 1st
