### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by cdiazsynapse** [EHDEN/ApplicationPortals#21]
We can keep Chamber of Commerce but we definitely need VAT Nr as well. It is more universally used. Without it, you cannot operate so I would make VAT Nr mandatory and Chamber of Commerce optional perhaps. 

Annual turnover needs a reference to currency. I suggest adding (EURO).

**Comment by PRijnbeek** [comment]
Yes, I remember we had this discussion in the forum. We could add this as well, but it may suggest we are going to pay them? Practically, we will probably not use the information and will look at the website more probably. Shall we remove it completely? risk there will non-companies applying is very limited i think.

Agree, I added (euro) now in the field name.

**Comment by cdiazsynapse** [comment]
No, in practice the VAT Nr acts as proof that the company exists. No one will understand that it implies any payment.

**Comment by PRijnbeek** [comment]
Ok we will add it after these tests are done (cannot add it now when forms are being filled in). We close it afterwards.

**Comment by PRijnbeek** [comment]
VAT Number is added.
