### ISSUE TITLE
Application form

### ISSUE THREAD

**Issue by cdiazsynapse** [EHDEN/ApplicationPortals#22]
There are some issues with the use of 'was' and 'is' in some of the questions. For past examples, I would use 'was', for experience they have, in some questions it is better 'is' or 'has been' (e.g. what has been your role...), but native speakers will be able to better advise..

The SAVE button definitely needs to be a COMPLETE or FINALISE or something. Otherwise can be easily mistaken for what the SAVE DRAFT button actually does.

The signature at the bottom, to simulate a real signature, could include a text box in which the person filling in the form types his/her name (keeping the checkbox too).

**Comment by PRijnbeek** [comment]
Yes also noted by Matt will double check.

I do not remember if it is mentioned on the top of the form, but save draft and save are the same if you filled in all mandatory fields, save draft allows you to save a not completely filled in form (submit button will not be green)

Signature: we could, will check


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by PRijnbeek** [comment]
text:
Looked at these again, changed a view. 

save button:
We cannot change this. 

Signature:
Yes changed now to a Declaration Check box and then as in the Agreement Form a signature field to fill in the name.
