### ISSUE TITLE
Re-open submitted application?

### ISSUE THREAD

**Issue by cdiazsynapse** [EHDEN/ApplicationPortals#23]
This may not be supported by Wizehive, but I think it is very likely that people submit and then remember they should have said this or that... A 'Re-open submission' available until the deadline would be great. Otherwise I fear some may even initiate a new application and we will end up with duplicates (we can always take the most recent, but still). I think this safeguard of being able to re-open would be great.  

If it cannot be implemented, we have to make it more apparent (perhaps a confirmation pop up - are you sure?) that by clicking on submit applicants will no longer be able to modify anything. When they 'SAVE' they can still modify things I presume?

**Comment by PRijnbeek** [comment]
I see the point. This can be made more explicit in the submit steps. This is why the save and save draft are there in a separate step.

If you submit you submit. If you like to change we can open it again but we should not stimulate/mention that.

Save draft: allows save without the needed fields check

Save will warn if you have forgotten things.

If you have filled in everything even when you clicked save draft the submit button will be Green.




Sent with BlackBerry Work
(www.blackberry.com)

**Comment by cdiazsynapse** [comment]
so then perhaps just make sure that there is a very obvious warning before clicking on 'submit'

**Comment by PRijnbeek** [comment]
Yes we can add it in that box next to the button no other options in the system i have seen but will ask.


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by PRijnbeek** [comment]
I have added a bold text stating that the application cannot be updated once submitted and also added this text after submission: "Your application is now in the process of being reviewed and cannot be changed anymore in the submission portal. You will be contacted if any additional information is needed."
