### ISSUE TITLE
Email application approved

### ISSUE THREAD

**Issue by cdiazsynapse** [EHDEN/ApplicationPortals#25]
Suggestion of text based on the current one:

On behalf of the European Health Data and Evidence Network (EHDEN) Consortium, we would like to thank you for your interest and inform you that the SME Certification Committee has decided to accept your application for the EHDEN training and certification programme.  
We are looking forward to collaborating with you to create a thriving ecosystem that generates reliable evidence to improve patient outcomes. Once certified, we expect your company to act as an enabler to facilitate data sources participation in large-scale, federated studies using state-of-the art analytical tools. We hope that our certification programme will enable you and other SMEs to play a pivotal role in EHDEN’s work developing a dynamic research community. 
We hope that you will also become an active member of such community, contributing to the development of tools, processes and activity around the OMOP CDM and OHDSI tools within EHDEN. 
Great that you will be part of this exciting journey! 
The next step is to sign the agreement to participate in the programme through the application portal. Once you have signed the agreement in the portal, we will contact you for the next steps. 
For any questions, please send an email to: enquiries@ehden.eu
The EHDEN Team.

**Comment by PRijnbeek** [comment]
Thanks Carlos, i like it.

This builds upon 
closed post: https://forum.ehden.eu/t/sme-acceptance-letter-for-certification-and-training/311/8
and this request of last week: https://forum.ehden.eu/t/input-needed-on-the-auto-emails/316

Suggest we do not re-iterate it again in the team after this change for this call round. @nigehughes if you are okay English wise we make this the final text for Pilot Call 1.

**Comment by nigehughes** [comment]
Agreed, and all good for me as the EHDEN native English speaker reviewer ;-)

What if we don't accept/reject - what will we say?

**Comment by PRijnbeek** [comment]
https://forum.ehden.eu/t/input-needed-on-the-auto-emails/316

I will also reject yours now... Procedure wise we can decide to then also send a separate email with reviewer summary, we will see when/if this happens.

**Comment by nigehughes** [comment]
But you promised you would not! ;-))

Btw, I note I did not receive any email following submission, was not sure if that was due to the platform, as it was still in beta? Should I submit as an issue?

**Comment by PRijnbeek** [comment]
The reason is you filled in this email address for the applicant
nige@fantasy-etl.be

See the help text below that field. You can change it yourself and I will put you in submitted mode and than in the rejected mode so you will receive all.

**Comment by nigehughes** [comment]
Which you told us not to do. I can only say I was carried away in the submission ;-)

I'll change it.

**Comment by PRijnbeek** [comment]
Updated the email text.
