### ISSUE TITLE
Street number missing in address

### ISSUE THREAD

**Issue by fgiesen** [EHDEN/ApplicationPortals#26]
In the Profile form, when SME is asked to enter an address, the street number field is missing (or should be included into the street name field).

**Comment by PRijnbeek** [comment]
Your are the second person that has an issue, interestingly i have almost never seen this in a form and it is the default to at the number (do search in google and look at images). What I suggest is to add this in the help text below the field.

**Comment by PRijnbeek** [comment]
Now called Street Address to avoid this confusion.
