### ISSUE TITLE
"Untitled" page for SME application page

### ISSUE THREAD

**Issue by fgiesen** [EHDEN/ApplicationPortals#27]
![image](https://user-images.githubusercontent.com/17162537/54430267-5828b100-4723-11e9-97a7-ecf45cbcc938.png)

In the SME application page, the title of the page in "Untitled".

**Comment by PRijnbeek** [comment]
Thanks will ask how this can be changed and will then close the issue.

**Comment by PRijnbeek** [comment]
Fixed.
