### ISSUE TITLE
Application Form Input	

### ISSUE THREAD

**Issue by jloliveira** [EHDEN/ApplicationPortals#28]
IMO, there are too many mandatory fields in this form. Considering that we are asking about skills and experience on very specific topics, some responders maybe do not have nothing to say in one or two questions.

**Comment by PRijnbeek** [comment]
Agree we can remove the mandatory requirement. If they did not fill in anything they are assumed not to have the skills. Once this is changed. I will close the issue.

**Comment by PRijnbeek** [comment]
Done. Only kept Signature as required. Will add some text in the instructions for SMEs that to increase their acceptance chance they should fill in all applicable fields or something like this. I close this issue now.
