### ISSUE TITLE
Application Form View said "Signed" although nothing was signed

### ISSUE THREAD

**Issue by fgiesen** [EHDEN/ApplicationPortals#29]
In the Application Form preview (with the eye), at the end of the preview, it is mentionned: "Signature signed".
But nothing was formerly signed in the process (neither submitted).

**Comment by PRijnbeek** [comment]
You checked the signature Box in the form that is why.

**Comment by PRijnbeek** [comment]
Changed this to Declaration checkbox instead of Signature with as value "Declared".

Signature is now replaced as in the acceptance form by asking them to type in the full name of the applicant.
