### ISSUE TITLE
Field checks and other remarks

### ISSUE THREAD

**Issue by bmosseveld** [EHDEN/ApplicationPortals#3]
**Applicant Profile Input**
- [x] Number of Employees should be forced to be a number.
- [ ] Telephone numbers should have an optional + at the beginning and then only numbers, spaces or dashes.
- [ ] An internet address should not be allowed to contain spaces.
- [x] What is expected at the LinkedIn field?

**Application Form**
- [ ] In "We invite you to add links (max 5) ...." I would use the word "references" instead of "links".

**Comment by PRijnbeek** [comment]
Will check how much validation we can add.

Links/references: yes we could maybe say both since if they have links i would prefer these.

**Comment by PRijnbeek** [comment]
Fixed the signed off items above. The other field validations were not possible.

I kept the add links, since links are best to get.
