### ISSUE TITLE
A date earlier/later than today can be filled in in signature

### ISSUE THREAD

**Issue by fgiesen** [EHDEN/ApplicationPortals#31]
In the Award Acceptance page, when user is required to sign, a date of signature earlier than the date of today can be entered. Similarilly, it is possible to sign at a date later than today. I would suggest to remove this field and force to display the date of today.

**Comment by PRijnbeek** [comment]
Agreed. The date will be stored in the portal automatically anyway when they submitt the form. So I have removed the date field.
