### ISSUE TITLE
Mobile signup page password checks

### ISSUE THREAD

**Issue by keesvanbochove** [EHDEN/ApplicationPortals#32]
When signing up for an account using a mobile phone, the password checks don't work when pasting a password from a password generation application (I use 1Password). Tried this in both Firefox Focus and Chrome on an Android phone.
It's a minor issue, most people will anyway probably use a desktop to sign up, but good to know that the password checks will only be applied if you type an extra letter into the password field.
![Screenshot_20190313-162012_Firefox Focus](https://user-images.githubusercontent.com/373418/54433740-dd649380-472c-11e9-83f5-262e73aef9f7.jpg)

**Comment by PRijnbeek** [comment]
I have informed WizeHive know about the bug. I will close this as issue for EHDEN since it will not create problems for us i think. If it does we have this logged in this issue and could re-open it.
