### ISSUE TITLE
SME Committee - Committee Review Profile

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#35]
I think it would be valuable to have a date linked to the committee members profile, to keep track of how long they have been in the committee (as we want to rotate)? Also, I don't know if you can see statistics but keeping track of how many reviews a certain member has done would also be nice?

**Comment by PRijnbeek** [comment]
1. Agree have now added a Profile Creation Date
2. We can see that in the backend. You click on the reviewer and then you can see the linked reviews.
