### ISSUE TITLE
SME Committee - Application overview

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#36]
I think that for the tab of the applications overview it would be very useful to have a column with the status of their application (perhaps as 1 of the first columns?). This would make it easy to see where we need to take action. At current, I could only see this by opening each individual application...

**Comment by PRijnbeek** [comment]
Agree and implemented:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/7252105/54539640-cd4fec80-4996-11e9-9aac-e39fb84bcd12.png">

Change the view to Status View
