### ISSUE TITLE
SME Committee - Review

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#37]
When the reviewer is asked whether they have a conflict of interested with the SME, and you pick yes, nothing happens (whereas you get questions to answer when you select no). Perhaps add a 1 line explanation here to say that they can just save the review without any further questions? I found it confusing compared to when you press no.

**Comment by PRijnbeek** [comment]
Yes agree will change that.

**Comment by PRijnbeek** [comment]
Add this in the help text
