### ISSUE TITLE
homepage

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#44]
At the bottom of profile it says:  " The Profile is always editable. You cannot start your application until you have completed the Profile." 

Underneath this I would add that they can contact us at enquiries@ehden.eu if they want to have their profile removed from the system? (Just to be compliant ;))

**Comment by JellePraet** [comment]
also on this homepage, there is the text : 
If the status bar is grey, in color, their application is in review status, and no action needs to be taken at the moment.
If the status bar is orange, that means that there is an action/step that the applicant needs to take. A form needs to be filled out, etc.
If the status bar is red, that means that there is an error and the applicant should reach out us at applicants@ehden.eu.

Remove the 'in color' in the first line + rephrase all 3 lines so they are directed at the applicant 'you don't need to take action) rather then in 3rd person (no action needs to be taken)

**Comment by PRijnbeek** [comment]
@JellePraet why enquiries@ehden.eu and not applicants@ehden.eu?

Yes that second text is the standard text but agree will change it.

**Comment by PRijnbeek** [comment]
added text at the end of the from. fixed text. refer to applicants@ehden.eu
