### ISSUE TITLE
Creating an application

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#45]
when i clicked on the card to start my application, the page which opens is labelled as homepage > Untitled.

**Comment by PRijnbeek** [comment]
Yes saw that too, however when you come back it looks ok.

**Comment by JellePraet** [comment]
The text on top says "If the application is granted after committee review, you will see additional steps to submit the Milestone Reports." 
Perhaps we should say: "We will notify you of the call result by email and if your application is granted ...

**Comment by PRijnbeek** [comment]
Both are fixed now.
