### ISSUE TITLE
The actual application

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/ApplicationPortals#46]
Based on my experience with the SME call, I felt that sometimes it was not 100% clear for the SME what kind of information we were looking for with certain questions, or what style of answers we wanted. As such, I'll give some feedback here on the questions that came to my mind when reading through it, so you can perhaps make it more clear what you want from the data source. 

Keep in mind that my feedback comes from a non-expert point of view, therefore some of it might be irrelevant. Just pointing out what's not clear to me...

* General issue: Perhaps on top of the page we should mention that we prefer to see "We are very experienced in A,B and C and have started to adopt D" rather then "A,B,C +++ / D + " Because some SMEs did answer like that and it's painful to read...

* **Provide a brief description of the data source** => Anything specific they need to mention?
* **Describe the geographic coverage** => Do you mean, are there data from other countries in the data base?
* **Is the data source containing patients with a specific socioeconomic status?** => I would guess every patient has his/her own specific status. Therefore I don't understand the question.
* **Is the data source containing patients from a specific health system (insured/uninsured, public vs. private)** => Same remark as the previous question. 
* **Data collection start and end fields** => Should this not be date fields?
* **total number of patients & number of active subjects** => Should these fields only allow numericals? 
* **For a description of these domains see https://github.com/OHDSI/CommonDataModel/wiki**	=> Can we make it a clickable URL?

* **Can you share the document on the database structure** => If they select no, ask them why not + Explain that this does not affect their application chances?

* **Do you want to share contact information?** => Seems like a very big field to say yes or no? 

* Under activity selection, perhaps also ask who's done the previous mappings? Might be interesting to know, as we might get to know some new SMEs this way?
* **Do you have documentation of the current data transformation?** => I can select both yes and no.
* **Can you share this documentation? =**> I can select both yes and no

**Comment by PRijnbeek** [comment]
Answering in order:

- Not sure what you like me to say here.
- Typical text you would put in a paper, they will know. Can add a hint.
- No for example certain regions / city in the country. Will add a hint
- It is about the word "specific" so are all patients on a certain status (Medicare in US for example). Will clarify in hint.
- Same thing
- Like to keep it as strings so they can add a clarification if they want.
- Same as above.
- Yes I can add this text in the presentational item using markdown
- That should actually happen let me check and fix that
- Yes agree
- Yes in case you select the B/C
- Ok will fix that
- Ok will fix that

Thanks will close the issue once all fixed.

**Comment by PRijnbeek** [comment]
Signed off above. Last four I will fix but will have to remove your application first for that.
