### ISSUE TITLE
Visiting and Postal Address

### ISSUE THREAD

**Issue by nigehughes** [EHDEN/ApplicationPortals#5]
It seemed to be a little annoying to fill our 'Visiting Address', and 'Postal Address'. There was an opportunity to confirm addresses are the same with a radio button at the end, but this seemed to be an afterthought.

Could there be a tick box at the end of 'Visiting Address' (or renamed Location?), to say contact address is the same?

**Comment by PRijnbeek** [comment]
Maybe we can leave Visiting Address out and have only one? If we need Visiting Address we can always ask. We can just call it Address?

Tickbox is possible yes as we do lower in the form

**Comment by cdiazsynapse** [comment]
agree, radio button or just one address

**Comment by PRijnbeek** [comment]
Now have only one address (no postal address) and for the applicant a radio button whether his address is the same as for the company.
