### ISSUE TITLE
Dani's notes/suggestions for improvement

### ISSUE THREAD

**Issue by daniprietoalhambra** [EHDEN/ApplicationPortals#52]
These are things we could do to improve the application:

1. I think we could give a bit more detail on what we expect at least for certain relevant sections like "Provide a brief description of the data source (max 250 words)". One could have the typical "?" button with further detail/instructions, eg here "Please describe here the type of data you have access to, including the number of participants currently registered, the average length of follow-up, ...". Or provide an example...
2. In the section on "Governance etc", should we add a question like "Are you allowed to use this data in collaboration with external parties?", with options "Yes, any"; "Yes, only academics"; or "Yes, any".. This is somewhat covered by the question "Are there any areas of use or research that have been explicitly barred by approval bodies or participants?" but I think it's better to have a specific multi-choice question on this very important issue. We don't want to engage with dcs that will then not want to collaborate in future research
3. the question "Which terminology systems are used in your database?" I guess refers to coding systems eg ICD9, ICD10 etc. Should we modify the wording of this question to "Which terminology/coding systems are used in your database?"

**Comment by PRijnbeek** [comment]
- [ ] 1. Most to the details are filled in later. We have added a hint "please use the short description you would normally use in a publication"

- [ ] 2. I see your point, i have added this question as free text with a hint in the form.

- [ ] 3. I have added a hint to make this more clear.
