### ISSUE TITLE
Data Partner application portal - Homepage

### ISSUE THREAD

**Issue by JellePraet1** [EHDEN/ApplicationPortals#54]
On the homepage, the applicants@ehden.eu is an empty mailto: function, it doesn't link the proper email address

**Comment by JellePraet1** [comment]
Same issue, when you created a profile, just above the box to start an application, the email doesn't link

**Comment by JellePraet1** [comment]
Perhaps also good to mention the application deadline on the homepage? I know it counts down, but seeing the actual date is better I think?

**Comment by PRijnbeek** [comment]
Not sure what you mean there is no email on the homepage? You mean once you are logged in?

It seems good to me.. what browser?
