### ISSUE TITLE
Verification Step envisioned?

### ISSUE THREAD

**Issue by toeresin** [EHDEN/ApplicationPortals#6]
There is no email verification step, so in case of an error in the email, the user might not recognise it or too late. 

Moreover we will reduce fake applications/fake sign ups by adding a verification step.

**Comment by PRijnbeek** [comment]
I will ask if this is possible and will reply here.

**Comment by PRijnbeek** [comment]
This is not possible at this moment, but I have added note about this in the Call Summary Text
