### ISSUE TITLE
Additional Questions

### ISSUE THREAD

**Issue by JellePraet1** [EHDEN/ApplicationPortals#61]
- [x] 1. I miss a question in the portal asking them to state the exact name of the legal entity that will be the recipient of the grant (just so we can make sure that no entity gets over 100k)

**Comment by JellePraet1** [comment]
Another question that I miss is: In case you succesfully receive a grant, is EHDEN allowed to mention your database name (and only it's name) in the project communications (eg. on the website, newsletter, ...)?

**Comment by apirraco** [comment]
A_When creating an applicant profile, the following was noted:_
**1.**Homepage > when clicking on the email address "applicants@ehden.eu" an email's window opens but the field 'TO" is empty> Is it supposed to be pre-populated with applicants@ehden.eu? (see below printscreen)
![Picture1](https://user-images.githubusercontent.com/81354629/112961745-effc6a80-9145-11eb-8334-b193ad73b889.png)

**2.** Creating Applicant profile > if applicant address is different from Data Partner > field "Country" are not drop down list as seen in the 'Contact Details" in the same form


B_When populating the application form the following was noted:_
**1.** Update hyperlink on  "For a description of the data domains in the CDM see the CDM Wiki Page" to go directly to https://ohdsi.github.io/CommonDataModel/ ?

**2.** Technical Details Section > Q4.Do you have a document available that describes the database structure? * A: Yes > Q5.Can you share this document? A: Yes > 6.Document uploaded but it is asked to Q7."Please explain why you cannot share the document *" ==> doesnt make sense. Possible to make Q7. conditional depending on Q5 reply?

**3.** Signature Section >Q4 "Can we add you to our newsletter so you will be notified of major milestones of EHDEN and future open calls?" > It allows multiple selection: both 'Yes" and "No". It should be one or the other.

**4** @PRijnbeek mentioned once to include a question to identify databases on vaccine or COVID patients (EMA suggestion) > Is this relevant? Should it be included?

C._General note_
1. Did not received any confirmation email, ie. created profile + application submitted > could not review emails

**Comment by PRijnbeek** [comment]
Thanks it would be better to make an issue per issue in the future because now we have to discuss multiple in one thread or group them as a "Missing Questions" Issue etc.

**Comment by apirraco** [comment]
1. @PRijnbeek and @JellePraet1 I always was able to see it

OK to close this issue
