### ISSUE TITLE
Application Profile

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/ApplicationPortals#69]
### Applicant profile

- [x] Homepage > when clicking on the email address "applicants@ehden.eu" an email's window opens but the field 'TO" is empty> Is it supposed to be pre-populated with applicants@ehden.eu? (see below printscreen)

![Picture1](https://user-images.githubusercontent.com/81354629/112961745-effc6a80-9145-11eb-8334-b193ad73b889.png)

- [x] Creating Applicant profile > if applicant address is different from Data Partner > field "Country" is not drop down list as seen in the 'Contact Details" in the same form

**Comment by PRijnbeek** [comment]
Second comment is saw why that is but I will not change it since others have already filled in free text and that would corrupt the form. I close that one too this is not an important change.

**Comment by apirraco** [comment]
- [ ] 1st comment > if action was taken , there is no change. The email field is still not appearing pre-populated to me

**Comment by PRijnbeek** [comment]
![image](https://user-images.githubusercontent.com/7252105/114675036-1c001a00-9d08-11eb-93a9-0e9ad3a9a365.png)


Works for me on the homepage

**Comment by apirraco** [comment]
tried again, for some reason it doesnt work for me. OK to close issue

**Comment by PRijnbeek** [comment]
Fixed
