### ISSUE TITLE
Password reset email ends up in Spam

### ISSUE THREAD

**Issue by toeresin** [EHDEN/ApplicationPortals#7]
The Password reset email ends up email, due to 
 -  Subject Line
 - missing "from" Information
and do on... (I'm no expert)

Spam checkers are available to avoid that the reset email ends up in the spam folder

**Comment by PRijnbeek** [comment]
Good point, we can add this in the instructions. Will also ask if this can be changed but not so sure about this. 

It did not end up in my spam folder, but could happen in more restrictive environments.

**Comment by PRijnbeek** [comment]
Will be added in the instructions and reported to WizeHive. Will close it for now since it will not impact release but will re-open and update if more information is received.
