### ISSUE TITLE
Application Form

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/ApplicationPortals#70]
- [x] 1.	Update hyperlink on "For a description of the data domains in the CDM see the CDM Wiki Page" to go directly to https://ohdsi.github.io/CommonDataModel/ ?
- [x] 2.	Signature Section >Q4 "Can we add you to our newsletter so you will be notified of major milestones of EHDEN and future open calls?" > It allows multiple selection: both 'Yes" and "No". It should be one or the other.

**Comment by apirraco** [comment]
- [ ] 3. Technical Details Section > Q4.Do you have a document available that describes the database structure? * A: Yes > Q5.Can you share this document? A: Yes > 6.Document uploaded but it is asked to Q7."Please explain why you cannot share the document *" ==> doesnt make sense. Possible to make Q7. conditional depending on Q5 reply?

**Comment by PRijnbeek** [comment]
All fixed please check and close issue.

**Comment by apirraco** [comment]
- [ ] 3. Q5: Y > Q7 is still visible (red arrows) it is not conditional; it seems to be fixed
![Picture1](https://user-images.githubusercontent.com/81354629/114724671-17edef80-9d3c-11eb-9ba0-3c93d17f7415.png)

**Comment by PRijnbeek** [comment]
Fixed
