### ISSUE TITLE
Confirmation Emails

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/ApplicationPortals#71]
Did not receive any confirmation email, ie. created profile + application submitted > could not review emails

**Comment by PRijnbeek** [comment]
These have now been activated. Please review and add any problems you found here in this issue

**Comment by apirraco** [comment]
Created a new profile and made new submission. No email was received.

**Comment by apirraco** [comment]
@PRijnbeek once more, created a new profile and submitted a mock application. No email received. I used my modis account and it worked well for the SME call so do not think the server is blocking. Let me know if I can be of further assistance.

**Comment by PRijnbeek** [comment]
I am receiving the emails just fine, but you have to fill in the correct applicant email in the signup form! 
<img width="882" alt="image" src="https://user-images.githubusercontent.com/7252105/114762283-dec87600-9d61-11eb-9baf-e1f7af87e8b1.png">

**Comment by apirraco** [comment]
Noted for next time!
