### ISSUE TITLE
DP#4 Reviewers Form

### ISSUE THREAD

**Issue by apirraco** [EHDEN/ApplicationPortals#74]
- [x] 1. **Third Criteria - change to reflect Call document** page 11 as below and [here](https://www.ehden.eu/wp-content/uploads/2021/04/Data-Partner-Call-Description-v5.0_FINAL.pdf) :

3. Readiness (Score 1-10): Score in terms of ability and willingness to actively participate in the EHDEN eco-system, including:
a. Willingness and ability to participate in federated network studies, including study
feasibility assessments.
b. Availability of information about applicable ethical and governance mechanisms for
use of the data in federated network studies.
c. Willingness and ability to share metadata about the data source to populate the
Database Catalogue.
In relation with metadata, please note that any EHDEN Data Partner will be requested to be included in the Database Catalogue with at least information about the data provenance, available domains of data, database size, univariate statistics on concept level, and the summary findings from the SME inspection. Data sources that are willing to share ]([url](url))the ETL documentation will receive a higher score.

- [x] 2.  Only available the option to evaluate **Complexity** as “low” or “high”. **Add option:  “medium”**

**Comment by PRijnbeek** [comment]
Fixed please check and close issue afterwards

**Comment by apirraco** [comment]
- [ ] 1. Third Criteria > Update the name from "Meta Data Sharing" to " Readiness"

![Picture1](https://user-images.githubusercontent.com/81354629/117788887-17b41780-b248-11eb-8ecc-d8b08ee06b60.png)

**Comment by apirraco** [comment]
Hi Pieter,

Could you please update the name of the 3rd criteria in the Reviewers form from: Meta Data Sharing to Readiness?

I have added this issue in Github as comment to the open issue.

Thank you and best wishes,
Ana

**Comment by PRijnbeek** [comment]
Done

**Comment by apirraco** [comment]
Dank je wel!
