### ISSUE TITLE
DP5 - Reviewers Portal - 

### ISSUE THREAD

**Issue by apirraco** [EHDEN/ApplicationPortals#79]
@PRijnbeek 

- [ ] On Network impact description, update last paragraph to read as follows:

•	Datasets with granular data will also be especially welcome. 
•	Datasets with longer term follow up, and in-patient data.
•	Including, but not exclusively Patient Outcomes, e.g., PROs/PREMs/HRQoL.
•	Including, but not exclusively Claims, resource utilization.
Specific interest for this call (but not exclusively):
•	Rare/autoimmune/inflammatory disease
•	Cancer therapies and registries, small rich datasets
•	Medical devices

**Comment by PRijnbeek** [comment]
Done.
