### ISSUE TITLE
SME Call#4 - Update portal deadline

### ISSUE THREAD

**Issue by apirraco** [EHDEN/ApplicationPortals#84]
@PRijnbeek Can you please update the deadline for the SME Call#4: will run from 15 Mar to 13 Apr. Thank you

**Comment by PRijnbeek** [comment]
Done open till 6:00 ET

**Comment by apirraco** [comment]
Can you please change deadline to April 13  2022 at 17:00 CET.

Forgot to mention the time. Thanks!
