### ISSUE TITLE
SME Call#4 - Confirmation email re creating profile

### ISSUE THREAD

**Issue by apirraco** [EHDEN/ApplicationPortals#86]
@PRijnbeek 

With the update of the year, a new link to the portal was created.

Can you please replace link in body email of confirmation email sent when a profile is created?

- [ ] use new link (in below red box): 
![image](https://user-images.githubusercontent.com/81354629/157460768-842b26c1-6047-4197-9edf-71cfb102605c.png)

![image](https://user-images.githubusercontent.com/81354629/157461260-d4672535-5451-4d56-b7b6-5b52d2016c9e.png)

**Comment by PRijnbeek** [comment]
Done.
