### ISSUE TITLE
SME Call#4 - Reviewer cannot access portal

### ISSUE THREAD

**Issue by apirraco** [EHDEN/ApplicationPortals#88]
Hi @PRijnbeek, not sure the best way to reach out to you. I have also sent you a message via Teams. 
Apologies for the overload.

We just had our SMECC consensus meeting and Andries had issues entering the platform. The kept being directed to the main page to log in and at one point he got the following message:

![image](https://user-images.githubusercontent.com/81354629/160594277-ffbb0e6d-0738-48b8-9d2c-8a1318e289a8.png)

would you be able to advice? Many thanks!

**Comment by PRijnbeek** [comment]
I am not sure what the issue is. Does he have an account already and ever logged in before. If not we may need to start setting up the account again.
