### ISSUE TITLE
Application: This has been submitted. 

### ISSUE THREAD

**Issue by toeresin** [EHDEN/ApplicationPortals#9]
Can we add the date, when the applciation was submitted?

**Comment by PRijnbeek** [comment]
Can ask, but this would probably be a new feature request. We see the date in the backend of course and they receive the email on the date it was submitted.

I think you can still click on it to view it, does it not show the date there?

**Comment by PRijnbeek** [comment]
It does show the date there. We removed the date field see this post:
https://github.com/EHDEN/ApplicationPortals/issues/31

Closing the issue. @toeresin can re-open if needed.
